name: Terraform Workflow with OIDC and Artifact Upload

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required to access repository contents

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 3: Configure AWS Credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform_validate.log
        run: terraform validate || echo "terraform validate failed"

      # Step 6: Terraform Plan
      - name: Terraform Plan
        env:
          TF_LOG: INFO
          TF_LOG_PATH: terraform_plan.log
        run: terraform plan -out=tfplan || echo "terraform plan failed"

      # Step 7: Terraform Apply
      - name: Terraform Apply
        env:
          TF_LOG: TRACE
          TF_LOG_PATH: terraform_apply.log
        run: terraform apply -auto-approve tfplan || echo "terraform apply failed"

      # Step 8: Capture Logs and Save as Artifacts
      - name: Capture Logs and Save as Artifacts
        if: always()  # Ensure this step runs even if the previous steps fail
        run: |
          mkdir -p $GITHUB_WORKSPACE/logs
          # Ensure logs exist and copy them
          if [ -f terraform_validate.log ]; then cp terraform_validate.log $GITHUB_WORKSPACE/logs/; fi
          if [ -f terraform_plan.log ]; then cp terraform_plan.log $GITHUB_WORKSPACE/logs/; fi
          if [ -f terraform_apply.log ]; then cp terraform_apply.log $GITHUB_WORKSPACE/logs/; fi
        continue-on-error: true  # Ensure this step doesn't stop the workflow if something fails

      # Step 9: Upload Logs as Artifacts
      - name: Upload Terraform Logs as Artifacts
        if: always()  # Upload artifacts even if the workflow fails
        uses: actions/upload-artifact@v3
        with:
          name: terraform-logs
          path: $GITHUB_WORKSPACE/logs/

      # Step 10: Print Logs on Failure
      - name: Print Logs on Failure
        if: failure()
        run: |
          echo "Terraform failed. Logs are as follows:"
          cat terraform_validate.log || true
          cat terraform_plan.log || true
          cat terraform_apply.log || true
