name: Terraform Workflow with OIDC and Artifact Upload 

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required to access repository contents

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 3: Configure AWS Credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        continue-on-error: true  # Continue even if it fails
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform_validate.log
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        continue-on-error: true  # Continue even if it fails
        env:
          TF_LOG: INFO
          TF_LOG_PATH: terraform_plan.log
        run: terraform plan -out=tfplan

      # Step 7: Terraform Apply
      - name: Terraform Apply
        continue-on-error: true  # Continue even if it fails
        env:
          TF_LOG: TRACE
          TF_LOG_PATH: terraform_apply.log
        run: terraform apply -auto-approve tfplan

      # Step 8: Ensure Logs Directory Exists
      - name: Ensure Logs Directory Exists
        run: mkdir -p $GITHUB_WORKSPACE/logs

      # Step 9: Copy Logs to Logs Directory
      - name: Copy Logs to Logs Directory
        run: |
          echo "Checking if log files exist"
          if [ -f terraform_validate.log ]; then
            echo "terraform_validate.log exists, copying to logs directory."
            cp terraform_validate.log $GITHUB_WORKSPACE/logs/
          fi
          if [ -f terraform_plan.log ]; then
            echo "terraform_plan.log exists, copying to logs directory."
            cp terraform_plan.log $GITHUB_WORKSPACE/logs/
          fi
          if [ -f terraform_apply.log ]; then
            echo "terraform_apply.log exists, copying to logs directory."
            cp terraform_apply.log $GITHUB_WORKSPACE/logs/
          fi
          echo "Files in logs directory:"
          ls -alh $GITHUB_WORKSPACE/logs/

      # Step 10: Upload Terraform Logs as Artifacts
      - name: Upload Terraform Logs as Artifacts
        if: always()  # Upload artifacts even if the workflow fails
        uses: actions/upload-artifact@v3
        with:
          name: terraform-logs
          path: $GITHUB_WORKSPACE/logs/

      # Step 11: Ensure the Workflow Fails if Critical Steps Fail
      - name: Ensure Workflow Fails if Critical Steps Fail
        if: failure()  # Only run if previous steps fail
        run: |
          echo "Terraform failed. The workflow will now exit with a failure status."
          exit 1
