name: Terraform Workflow with OIDC and Artifact Upload

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required to access repository contents

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # Step 3: Configure AWS Credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform_validate.log
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        env:
          TF_LOG: INFO
          TF_LOG_PATH: terraform_plan.log
        run: terraform plan -out=tfplan

      # Step 7: Terraform Apply
      - name: Terraform Apply
        env:
          TF_LOG: TRACE
          TF_LOG_PATH: terraform_apply.log
        run: terraform apply -auto-approve tfplan

      # Step 8: Upload Artifacts (Logs)
      - name: Upload Terraform Logs as Artifacts
        if: always()  # Upload artifacts even if the workflow fails
        uses: actions/upload-artifact@v3
        with:
          name: terraform-logs
          path: |
            terraform_validate.log
            terraform_plan.log
            terraform_apply.log

      # Step 9: Print Logs on Failure
      - name: Print Logs on Failure
        if: failure()
        run: |
          echo "Terraform failed. Logs are as follows:"
          cat terraform_validate.log || true
          cat terraform_plan.log || true
          cat terraform_apply.log || true
