name: Destroy Terraform Workflow

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Destroy Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: TerraformDestroySession

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      continue-on-error: true
      env:
        TF_LOG: TRACE
        TF_LOG_PATH: terraform_destroy.log
      run: terraform destroy -auto-approve

    - name: Ensure Logs Directory Exists
      run: mkdir -p $GITHUB_WORKSPACE/logs

    - name: Copy Terraform Destroy Logs to Logs Directory
      run: |
        if [ -f terraform_destroy.log ]; then
          cp terraform_destroy.log $GITHUB_WORKSPACE/logs/
        fi

    - name: Print Logs on Failure
      if: failure()
      run: |
        echo "Terraform Destroy failed. Logs are as follows:"
        cat $GITHUB_WORKSPACE/logs/terraform_destroy.log || true

    - name: Upload Terraform Destroy Logs as Artifacts
      if: always()  # This will always run
      uses: actions/upload-artifact@v3
      with:
        name: terraform-destroy-logs
        path: logs/

    - name: Force Workflow Failure if Terraform Destroy fails
      if: failure()
      run: |
        echo "Terraform Destroy failed. Marking workflow as failed."
        exit 1

